### PR TITLE
Collision Avoidance Feature (aka Basic obstacle avoidance)

### PR DESCRIPTION
**Pull request by leithhobson**
In this pull request, we have implemented a basic collision avoidance feature.
This is referred to as "Basic obstacle avoidance" in the relevant assignment.

### CODE REVIEW

**Review by platisd — COMMENTED** [review]
This is such a big pull request for such a small feature (at least according to the title).
It's not a good practice to do so. :)

You should avoid merging unrelated things in the same pull request but instead commit and merge often. Additionally, you should point out where the assignment's task is implemented.

**Comment by leithhobson** [comment]
> unrelated things in the same pull request but instead



> This is such a big pull request for such a small feature (at least according to the title).
> It's not a good practice to do so. :)
> 
> You should avoid merging unrelated things in the same pull request but instead commit and merge often. Additionally, you should point out where the assignment's task is implemented.

@platisd I appreciate your comment. 
The reason for the pull request being overly large is that we had to build the foundation of the code that will run on the car, and, in effect, the entire car folder is our response to the assignment. That said however, I will re-submit the assignment, with a new pull request, that contains only one sketch, which meets the requirements of the task, but does not contain additional code.

**Comment by platisd** [comment]
Splitting it up in smaller pull requests would be the right thing to do. :)

**Comment by leithhobson** [comment]
> Splitting it up in smaller pull requests would be the right thing to do. :)

Thank you

**Review by diaistanbuly — APPROVED** [review]

**Comment by AeroStun** [comment]
@istanbuly You realize by pushing ece2653 you just put IDE-internal files and build binaries right?
Edit: Fixed by #18

**Pull request merged**
